<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIaPZ9X9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIaPZ9X9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIaPZ9X9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIaPZ9X9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIaPZ9X9\App_KernelDevDebugContainer([
    'container.build_hash' => 'IaPZ9X9',
    'container.build_id' => '9e4a93a1',
    'container.build_time' => 1631000495,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIaPZ9X9');
